version: "25.0.2"
services:
  api:
    build: ./server
    container_name: speedtest-server
    ports:
      - "3025:3025"
    volumes:
      - ./server:/speedtest-server
      - /server/node_modules
  # client:
  #   build: ./client/react
  #   container_name: speedtest-client
  #   ports:
  #     - '3000:3000'
  #   # wont work in windows
  #   # volumes:
  #   #   - ./client/react:/speedtest-client
  #   stdin_open: true
  #   tty: true
  jsservices:
    build: ./services/javascript
    container_name: speedtest-services-intspeeds
    ports:
      - "3001:3001"
    volumes:
      - ./services/javascript:/speedtest-services-intspeeds
      - /services/javascript/node_modules
  # pyservices:
  #   build: ./services/python
  #   container_name: speedtest-services-externalspeeds
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #     - ./services/python:/speedtest-services-externalspeeds
  #     - /services/python/__pycache__
  #   depends_on:
  #     - api
