version: "3.8"
services:
  api:
    build: .
    container_name: speedtest-server
    ports:
      - "4001:4001"
    volumes:
      - ./:/speedtest-server
      - /speedtest-server/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true  # This allows interactive commands (optional)
    tty: true         # This allows for TTY (optional)
    command: npm run dev