version: "25.0.2"
services:
  api:
    build: /
    container_name: speedtest-server
    ports:
      - "4001:4001"
    volumes:
      - ./:/speedtest-server
      - /node_modules
#     networks:
#       - docker-network
# networks:
#   docker-network:
#     external: true
