version: "25.0.2"
services:
  pyservices:
    build: /
    container_name: speedtest-services-externalspeeds
    ports:
      - "3002:3002"
    volumes:
      - ./:/speedtest-services-externalspeeds
      - /__pycache__
#     networks:
#       - docker-network
# networks:
#   docker-network:
#     external: true