version: "25.0.2"
services:
  client:
    build: /
    container_name: speedtest-client
    ports:
      - '3000:3000'
    # wont work in windows
    # volumes:
    #   - ./client/react:/speedtest-client
    stdin_open: true
    tty: true

